accounts:
  - name: alice
    coins: ["200000000ctok"]
  - name: bob
    coins: ["100000000ctok"]
validator:
  name: alice
  staked: "100000000ctok"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ctok"
    crisis:
      constant_fee:
        denom: "ctok"
    gov:
      deposit_params:
        min_deposit:
          denom: "ctok"
    mint:
      params:
        mint_denom: "ctok"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5ctok"]
