// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: offerservice/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetAllCharOffersRequest struct {
	CharId     string             `protobuf:"bytes,1,opt,name=charId,proto3" json:"charId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllCharOffersRequest) Reset()         { *m = QueryGetAllCharOffersRequest{} }
func (m *QueryGetAllCharOffersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllCharOffersRequest) ProtoMessage()    {}
func (*QueryGetAllCharOffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{0}
}
func (m *QueryGetAllCharOffersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllCharOffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllCharOffersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllCharOffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllCharOffersRequest.Merge(m, src)
}
func (m *QueryGetAllCharOffersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllCharOffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllCharOffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllCharOffersRequest proto.InternalMessageInfo

func (m *QueryGetAllCharOffersRequest) GetCharId() string {
	if m != nil {
		return m.CharId
	}
	return ""
}

func (m *QueryGetAllCharOffersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAllCharOffersResponse struct {
	OfferContract []*OfferContract    `protobuf:"bytes,1,rep,name=OfferContract,proto3" json:"OfferContract,omitempty"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllCharOffersResponse) Reset()         { *m = QueryGetAllCharOffersResponse{} }
func (m *QueryGetAllCharOffersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllCharOffersResponse) ProtoMessage()    {}
func (*QueryGetAllCharOffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{1}
}
func (m *QueryGetAllCharOffersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllCharOffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllCharOffersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllCharOffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllCharOffersResponse.Merge(m, src)
}
func (m *QueryGetAllCharOffersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllCharOffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllCharOffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllCharOffersResponse proto.InternalMessageInfo

func (m *QueryGetAllCharOffersResponse) GetOfferContract() []*OfferContract {
	if m != nil {
		return m.OfferContract
	}
	return nil
}

func (m *QueryGetAllCharOffersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetOfferContractRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetOfferContractRequest) Reset()         { *m = QueryGetOfferContractRequest{} }
func (m *QueryGetOfferContractRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetOfferContractRequest) ProtoMessage()    {}
func (*QueryGetOfferContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{2}
}
func (m *QueryGetOfferContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetOfferContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetOfferContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetOfferContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetOfferContractRequest.Merge(m, src)
}
func (m *QueryGetOfferContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetOfferContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetOfferContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetOfferContractRequest proto.InternalMessageInfo

func (m *QueryGetOfferContractRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetOfferContractResponse struct {
	OfferContract *OfferContract `protobuf:"bytes,1,opt,name=OfferContract,proto3" json:"OfferContract,omitempty"`
}

func (m *QueryGetOfferContractResponse) Reset()         { *m = QueryGetOfferContractResponse{} }
func (m *QueryGetOfferContractResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetOfferContractResponse) ProtoMessage()    {}
func (*QueryGetOfferContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{3}
}
func (m *QueryGetOfferContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetOfferContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetOfferContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetOfferContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetOfferContractResponse.Merge(m, src)
}
func (m *QueryGetOfferContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetOfferContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetOfferContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetOfferContractResponse proto.InternalMessageInfo

func (m *QueryGetOfferContractResponse) GetOfferContract() *OfferContract {
	if m != nil {
		return m.OfferContract
	}
	return nil
}

type QueryAllOfferContractRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllOfferContractRequest) Reset()         { *m = QueryAllOfferContractRequest{} }
func (m *QueryAllOfferContractRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllOfferContractRequest) ProtoMessage()    {}
func (*QueryAllOfferContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{4}
}
func (m *QueryAllOfferContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllOfferContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllOfferContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllOfferContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllOfferContractRequest.Merge(m, src)
}
func (m *QueryAllOfferContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllOfferContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllOfferContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllOfferContractRequest proto.InternalMessageInfo

func (m *QueryAllOfferContractRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllOfferContractResponse struct {
	OfferContract []*OfferContract    `protobuf:"bytes,1,rep,name=OfferContract,proto3" json:"OfferContract,omitempty"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllOfferContractResponse) Reset()         { *m = QueryAllOfferContractResponse{} }
func (m *QueryAllOfferContractResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllOfferContractResponse) ProtoMessage()    {}
func (*QueryAllOfferContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4183cb6cde389cf9, []int{5}
}
func (m *QueryAllOfferContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllOfferContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllOfferContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllOfferContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllOfferContractResponse.Merge(m, src)
}
func (m *QueryAllOfferContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllOfferContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllOfferContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllOfferContractResponse proto.InternalMessageInfo

func (m *QueryAllOfferContractResponse) GetOfferContract() []*OfferContract {
	if m != nil {
		return m.OfferContract
	}
	return nil
}

func (m *QueryAllOfferContractResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetAllCharOffersRequest)(nil), "charactertoken.ctok.offerservice.QueryGetAllCharOffersRequest")
	proto.RegisterType((*QueryGetAllCharOffersResponse)(nil), "charactertoken.ctok.offerservice.QueryGetAllCharOffersResponse")
	proto.RegisterType((*QueryGetOfferContractRequest)(nil), "charactertoken.ctok.offerservice.QueryGetOfferContractRequest")
	proto.RegisterType((*QueryGetOfferContractResponse)(nil), "charactertoken.ctok.offerservice.QueryGetOfferContractResponse")
	proto.RegisterType((*QueryAllOfferContractRequest)(nil), "charactertoken.ctok.offerservice.QueryAllOfferContractRequest")
	proto.RegisterType((*QueryAllOfferContractResponse)(nil), "charactertoken.ctok.offerservice.QueryAllOfferContractResponse")
}

func init() { proto.RegisterFile("offerservice/query.proto", fileDescriptor_4183cb6cde389cf9) }

var fileDescriptor_4183cb6cde389cf9 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x77, 0xaa, 0x2d, 0x38, 0x45, 0x28, 0x83, 0xc8, 0xb2, 0xd4, 0xb0, 0xe6, 0xa0, 0x8b,
	0x87, 0x19, 0x36, 0x2d, 0x14, 0x3d, 0x58, 0xd6, 0x82, 0xc5, 0x83, 0xa8, 0x01, 0x2f, 0x5e, 0x64,
	0x92, 0xce, 0x66, 0x43, 0xd3, 0x99, 0x34, 0x33, 0xbb, 0xb4, 0x88, 0x1e, 0xfc, 0x04, 0x82, 0x1f,
	0xc8, 0xab, 0x07, 0xc1, 0x8a, 0x17, 0x8f, 0xb2, 0xeb, 0xc7, 0xf0, 0x20, 0x99, 0x0c, 0xec, 0x4e,
	0x4c, 0x4c, 0xd7, 0x9e, 0x7a, 0x9c, 0xf0, 0xbe, 0xcf, 0xfb, 0xfc, 0xde, 0x3f, 0x81, 0x6d, 0x31,
	0x1c, 0xb2, 0x4c, 0xb2, 0x6c, 0x12, 0x87, 0x8c, 0x1c, 0x8f, 0x59, 0x76, 0x8a, 0xd3, 0x4c, 0x28,
	0x81, 0xba, 0xe1, 0x88, 0x66, 0x34, 0x54, 0x2c, 0x53, 0xe2, 0x90, 0x71, 0x1c, 0x2a, 0x71, 0x88,
	0x17, 0xa3, 0x3b, 0x9b, 0x91, 0x10, 0x51, 0xc2, 0x08, 0x4d, 0x63, 0x42, 0x39, 0x17, 0x8a, 0xaa,
	0x58, 0x70, 0x59, 0xe4, 0x77, 0xee, 0x85, 0x42, 0x1e, 0x09, 0x49, 0x02, 0x2a, 0x8d, 0x30, 0x99,
	0xf4, 0x03, 0xa6, 0x68, 0x9f, 0xa4, 0x34, 0x8a, 0xb9, 0x0e, 0x36, 0xb1, 0xb7, 0x2d, 0x17, 0xfa,
	0xf1, 0x3a, 0x14, 0x5c, 0xe5, 0xf5, 0x8b, 0x10, 0xf7, 0x1d, 0xdc, 0x7c, 0x91, 0x8b, 0xec, 0x33,
	0x35, 0x48, 0x92, 0xbd, 0x11, 0xcd, 0x9e, 0xe9, 0x1c, 0x9f, 0x1d, 0x8f, 0x99, 0x54, 0xe8, 0x26,
	0x5c, 0xcb, 0x0d, 0x3f, 0x39, 0x68, 0x83, 0x2e, 0xe8, 0x5d, 0xf3, 0xcd, 0x0b, 0x3d, 0x86, 0x70,
	0x5e, 0xae, 0xbd, 0xd2, 0x05, 0xbd, 0x75, 0xef, 0x0e, 0x2e, 0xbc, 0xe1, 0xdc, 0x1b, 0x2e, 0xa0,
	0x8d, 0x37, 0xfc, 0x9c, 0x46, 0xcc, 0x68, 0xfa, 0x0b, 0x99, 0xee, 0x27, 0x00, 0x6f, 0xd5, 0x18,
	0x90, 0xa9, 0xe0, 0x92, 0xa1, 0x97, 0xf0, 0xba, 0xfe, 0xb2, 0x67, 0x8c, 0xb7, 0x41, 0xf7, 0x4a,
	0x6f, 0xdd, 0x23, 0xb8, 0xa9, 0x91, 0xd8, 0x4a, 0xf3, 0x6d, 0x15, 0xb4, 0x5f, 0x01, 0x70, 0xb7,
	0x11, 0xa0, 0xf0, 0x64, 0x11, 0x6c, 0xcf, 0x3b, 0x68, 0x17, 0x34, 0x1d, 0xbc, 0x01, 0x57, 0x63,
	0x7e, 0xc0, 0x4e, 0x4c, 0x03, 0x8b, 0x87, 0x3b, 0x99, 0x63, 0x97, 0xb2, 0xea, 0xb1, 0xc1, 0xc5,
	0xb1, 0xdd, 0xa1, 0x71, 0x3b, 0x48, 0x92, 0x4a, 0xb7, 0xf6, 0x5c, 0xc1, 0xc5, 0xe7, 0xfa, 0x77,
	0xa1, 0xcb, 0x31, 0x57, 0xef, 0xf7, 0x55, 0xb8, 0xaa, 0x09, 0xd0, 0x57, 0x00, 0x37, 0xca, 0xeb,
	0x89, 0x1e, 0x36, 0xfb, 0xfc, 0xd7, 0x61, 0x75, 0x76, 0xff, 0x3b, 0xbf, 0xf0, 0xea, 0x3e, 0x78,
	0xff, 0xfd, 0xd7, 0xc7, 0x95, 0x6d, 0xe4, 0x11, 0x5b, 0x88, 0xe4, 0x42, 0xc4, 0xba, 0xfc, 0xa8,
	0x6c, 0xfe, 0x1b, 0x28, 0x35, 0x7f, 0x19, 0x9c, 0xaa, 0xbd, 0x59, 0x06, 0xa7, 0x72, 0x1d, 0xdc,
	0x5d, 0x8d, 0x73, 0x1f, 0xed, 0x34, 0xe3, 0x88, 0x45, 0x01, 0xf2, 0x46, 0x1f, 0xd4, 0x5b, 0xf4,
	0x05, 0xc0, 0x0d, 0x4b, 0x7a, 0x90, 0x24, 0xe7, 0xc6, 0xaa, 0x39, 0x87, 0x73, 0x63, 0xd5, 0x6d,
	0xb9, 0xbb, 0xa3, 0xb1, 0xfa, 0x88, 0x2c, 0x89, 0xf5, 0xe8, 0xe9, 0xe7, 0xa9, 0x03, 0xce, 0xa6,
	0x0e, 0xf8, 0x39, 0x75, 0xc0, 0x87, 0x99, 0xd3, 0x3a, 0x9b, 0x39, 0xad, 0x1f, 0x33, 0xa7, 0xf5,
	0x6a, 0x2b, 0x8a, 0xd5, 0x68, 0x1c, 0xe0, 0x50, 0x1c, 0x55, 0x8a, 0x9e, 0xd8, 0xb2, 0xea, 0x34,
	0x65, 0x32, 0x58, 0xd3, 0xbf, 0xfb, 0xad, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0xc4, 0xd8,
	0xb9, 0x99, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of getAllCharOffers items.
	GetAllCharOffers(ctx context.Context, in *QueryGetAllCharOffersRequest, opts ...grpc.CallOption) (*QueryGetAllCharOffersResponse, error)
	// Queries a offerContract by index.
	OfferContract(ctx context.Context, in *QueryGetOfferContractRequest, opts ...grpc.CallOption) (*QueryGetOfferContractResponse, error)
	// Queries a list of offerContract items.
	OfferContractAll(ctx context.Context, in *QueryAllOfferContractRequest, opts ...grpc.CallOption) (*QueryAllOfferContractResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAllCharOffers(ctx context.Context, in *QueryGetAllCharOffersRequest, opts ...grpc.CallOption) (*QueryGetAllCharOffersResponse, error) {
	out := new(QueryGetAllCharOffersResponse)
	err := c.cc.Invoke(ctx, "/charactertoken.ctok.offerservice.Query/GetAllCharOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OfferContract(ctx context.Context, in *QueryGetOfferContractRequest, opts ...grpc.CallOption) (*QueryGetOfferContractResponse, error) {
	out := new(QueryGetOfferContractResponse)
	err := c.cc.Invoke(ctx, "/charactertoken.ctok.offerservice.Query/OfferContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OfferContractAll(ctx context.Context, in *QueryAllOfferContractRequest, opts ...grpc.CallOption) (*QueryAllOfferContractResponse, error) {
	out := new(QueryAllOfferContractResponse)
	err := c.cc.Invoke(ctx, "/charactertoken.ctok.offerservice.Query/OfferContractAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of getAllCharOffers items.
	GetAllCharOffers(context.Context, *QueryGetAllCharOffersRequest) (*QueryGetAllCharOffersResponse, error)
	// Queries a offerContract by index.
	OfferContract(context.Context, *QueryGetOfferContractRequest) (*QueryGetOfferContractResponse, error)
	// Queries a list of offerContract items.
	OfferContractAll(context.Context, *QueryAllOfferContractRequest) (*QueryAllOfferContractResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetAllCharOffers(ctx context.Context, req *QueryGetAllCharOffersRequest) (*QueryGetAllCharOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCharOffers not implemented")
}
func (*UnimplementedQueryServer) OfferContract(ctx context.Context, req *QueryGetOfferContractRequest) (*QueryGetOfferContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferContract not implemented")
}
func (*UnimplementedQueryServer) OfferContractAll(ctx context.Context, req *QueryAllOfferContractRequest) (*QueryAllOfferContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferContractAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetAllCharOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllCharOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllCharOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charactertoken.ctok.offerservice.Query/GetAllCharOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllCharOffers(ctx, req.(*QueryGetAllCharOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OfferContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetOfferContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OfferContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charactertoken.ctok.offerservice.Query/OfferContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OfferContract(ctx, req.(*QueryGetOfferContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OfferContractAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllOfferContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OfferContractAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charactertoken.ctok.offerservice.Query/OfferContractAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OfferContractAll(ctx, req.(*QueryAllOfferContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "charactertoken.ctok.offerservice.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllCharOffers",
			Handler:    _Query_GetAllCharOffers_Handler,
		},
		{
			MethodName: "OfferContract",
			Handler:    _Query_OfferContract_Handler,
		},
		{
			MethodName: "OfferContractAll",
			Handler:    _Query_OfferContractAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offerservice/query.proto",
}

func (m *QueryGetAllCharOffersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllCharOffersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllCharOffersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CharId) > 0 {
		i -= len(m.CharId)
		copy(dAtA[i:], m.CharId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CharId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllCharOffersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllCharOffersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllCharOffersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OfferContract) > 0 {
		for iNdEx := len(m.OfferContract) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfferContract[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetOfferContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetOfferContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetOfferContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetOfferContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetOfferContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetOfferContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OfferContract != nil {
		{
			size, err := m.OfferContract.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllOfferContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllOfferContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllOfferContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllOfferContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllOfferContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllOfferContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OfferContract) > 0 {
		for iNdEx := len(m.OfferContract) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfferContract[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetAllCharOffersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CharId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllCharOffersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OfferContract) > 0 {
		for _, e := range m.OfferContract {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetOfferContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetOfferContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OfferContract != nil {
		l = m.OfferContract.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllOfferContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllOfferContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OfferContract) > 0 {
		for _, e := range m.OfferContract {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetAllCharOffersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllCharOffersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllCharOffersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CharId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CharId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllCharOffersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllCharOffersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllCharOffersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferContract", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferContract = append(m.OfferContract, &OfferContract{})
			if err := m.OfferContract[len(m.OfferContract)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetOfferContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetOfferContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetOfferContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetOfferContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetOfferContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetOfferContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferContract", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OfferContract == nil {
				m.OfferContract = &OfferContract{}
			}
			if err := m.OfferContract.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllOfferContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllOfferContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllOfferContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllOfferContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllOfferContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllOfferContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferContract", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferContract = append(m.OfferContract, &OfferContract{})
			if err := m.OfferContract[len(m.OfferContract)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
